name: starcoder-ft
workspace: PDK Demos
project: starcoder
debug: true
data:
  data_dir: "/data"
  download_directory: "/tmp"
integrations:
  pachyderm:
    pachd:
      host: 
      port: 
    proxy:
      scheme: http
      host: console.pachpe.com
      port: 80
    dataset:
      branch: 
      commit: 
      project: 
      repo: 
      token:
environment:
  environment_variables:
    - NCCL_DEBUG=WARN
    - https_proxy=
    - http_proxy=
    - DET_MASTER_CERT_FILE=noverify
    - AWS_CA_BUNDLE=
  image:
    cuda: bosterbuhrhpe/llm-codegen-ft:0.2
  pod_spec:
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: determined-container
        volumeMounts:
        - mountPath: /cache
          name: cdr-cache
      volumes:
      - name: cdr-cache
        persistentVolumeClaim:
          claimName: cdr-cache
resources:
  slots_per_trial: 1
  resource_pool: gpu-pool
searcher:
  name: single
  max_length:
    batches: 10
  metric: eval_loss
hyperparameters:
  training_arguments:
    learning_rate: .0001
entrypoint: >-
  python -m determined.launch.torch_distributed
  python finetune-mlde.py
  --model_path "/tmp/model"
  --dataset_name
  "/tmp"
  --split
  "train"
  --size_valid_set
  "100"
  --streaming
  --seq_length
  "2048"
  --max_steps
  "10"
  --batch_size
  "1"
  --input_column_name
  "question"
  --output_column_name
  "response"
  --gradient_accumulation_steps
  "16"
  --lr_scheduler_type
  "cosine"
  --num_warmup_steps
  1
  --weight_decay
  0.05
  --output_dir
  "./outputdir"
  --log_freq
  20
  --save_freq
  20
  --eval_freq
  20
max_restarts: 1
