pipeline:
  name: peft-merge
egress:
  URL: s3://pd-a-bucket/peft
transform:
  image: 'bosterbuhrhpe/peft:0.5'
  cmd:
    - python
    - peft_merge.py
    - '--input_path_peft'
    - /pfs/peft
    - '--model'
    - /pfs/model
    - '--output-dir'
    - /pfs/out
  secrets:
    - name: hf-token
      key: token
      envVar: HF_HOME
parallelismSpec:
  constant: '1'
outputBranch: master
resourceLimits:
  gpu:
    number: 1
    type: nvidia.com/gpu
resourceRequests:
  cpu: '2'
  disk: 1Gi
  memory: 8Gi
sidecarResourceRequests:
  cpu: 8
  disk: 1Gi
  memory: 16Gi
input:
  cross:
    - pfs:
        project: default
        name: model
        repo: hf-download-starcoder-model
        branch: master
        glob: /
    - pfs:
        project: default
        name: peft
        repo: training
        branch: master
        glob: /
datumTries: '1'
autoscaling: true